- name: Hugging Push
  uses: backendcloud/hugging-push@v0.2.3
  with:
    huggingface_repo: Rupesh1904/warehouse-rag-backend  # your Hugging Face repo/space
    hf_token: ${{ secrets.HF_TOKEN }}                  # your Hugging Face token stored as a GitHub secret
    repo_type: space                                   # specify it's a Space
    space_sdk: fastapi                                 # your SDK (fastapi or gradio)
    private: true                                     # if your space is private
