name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        uses: backendcloud/hugging-push@v0.2.3
        with:
          huggingface_repo: Rupesh1904/warehouse-rag-backend
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: Docker   # change if your Space is gradio/streamlit
          private: false      # or true, no quotes
